function vss = NCX_vss(Delta,K_1,K_2,K_3,K_4,K_5,K_6,e_0,gam_Cae,gam_Cai,gam_Nae,gam_Nai,gam_mem,kappa_3,kappa_6)
%NCX_VSS
%    VSS = NCX_VSS(DELTA,K_1,K_2,K_3,K_4,K_5,K_6,E_0,GAM_CAE,GAM_CAI,GAM_NAE,GAM_NAI,GAM_MEM,KAPPA_3,KAPPA_6)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    20-Oct-2017 12:51:07

t2 = gam_Nae.^2;
t3 = gam_Nai.^2;
t4 = gam_mem.^Delta;
vss = (K_1.*K_2.*K_3.*K_4.*K_5.*K_6.*e_0.*kappa_3.*kappa_6.*t4.*(gam_Cai.*gam_Nae.*t2-gam_Cae.*gam_Nai.*gam_mem.*t3))./(K_1.*K_3.*K_4.*K_5.*K_6.*gam_Cae.*kappa_3+K_1.*K_2.*K_3.*K_4.*K_6.*gam_Cai.*kappa_3+K_1.*K_2.*K_3.*K_5.*K_6.*gam_Cae.*gam_Cai.*kappa_3+K_1.*K_2.*K_4.*K_5.*K_6.*gam_Cae.*gam_Cai.*kappa_3+K_1.*K_2.*K_3.*K_4.*K_5.*gam_Cai.*gam_Nae.*kappa_3.*t2+K_2.*K_3.*K_4.*K_5.*K_6.*gam_Cae.*gam_Nai.*kappa_3.*t3+K_1.*K_3.*K_4.*K_5.*K_6.*gam_Nae.*kappa_6.*t2.*t4+K_1.*K_2.*K_4.*K_5.*K_6.*gam_Cai.*gam_Nae.*kappa_6.*t2.*t4+K_1.*K_2.*K_3.*K_4.*K_6.*gam_Nai.*gam_mem.*kappa_6.*t3.*t4+K_1.*K_2.*K_3.*K_5.*K_6.*gam_Cae.*gam_Nai.*gam_mem.*kappa_6.*t3.*t4+K_2.*K_3.*K_4.*K_5.*K_6.*gam_Nae.*gam_Nai.*kappa_6.*t2.*t3.*t4+K_1.*K_2.*K_3.*K_4.*K_5.*gam_Nae.*gam_Nai.*gam_mem.*kappa_6.*t2.*t3.*t4);
